In [1]:
%load_ext autoreload
%autoreload 2
import julia
import numpy as np

In [2]:
#j = julia.Julia()
#solver = j.include('mtp2_cov_solver.jl')

In [3]:
import mtp2_elliptical_solver

In [4]:
data = np.random.multivariate_normal(mean = np.zeros(4), cov = np.eye(4), size = 10000)

In [5]:
data

array([[-1.96770331, -0.46190052, -0.40639232, -1.23467624],
       [ 0.39960611, -0.83187227, -0.64220007,  1.72420743],
       [ 2.10912654,  0.48323865, -1.42729657, -0.70309604],
       ...,
       [ 1.64706492,  0.84825417,  1.01580937, -0.24184604],
       [-2.1003161 , -0.95267805,  0.42790455, -0.64015592],
       [ 0.65533048, -0.60439256, -0.650833  , -1.74170651]])

In [6]:
ans = mtp2_elliptical_solver.MTP2CovEstimator(data, 10000)

Correlation matrix in MTP2CovEstimator function
[[ 1.00000000e+00  7.14187057e-03  2.93692462e-03 -6.24795530e-03]
 [ 7.14187057e-03  1.00000000e+00 -5.75569021e-03  9.75499082e-04]
 [ 2.93692462e-03 -5.75569021e-03  1.00000000e+00  2.11877471e-03]
 [-6.24795530e-03  9.75499082e-04  2.11877471e-03  1.00000000e+00]]


In [7]:
print(ans)

[[-2.23985601e-06  2.84396253e-06  1.17560566e-07  2.67517021e-05]
 [ 9.22822370e-07 -2.97941327e-06 -1.28260334e-07  5.34645743e-06]
 [-2.13759926e-07 -1.63327271e-06 -4.76526531e-08  2.46589526e-06]
 [ 7.60031077e-07  4.79265536e-06 -9.30920896e-08 -4.00501134e-06]]
